
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'FFD6DA5AA87B2A08001A4E22F9AB3853'
    
_lr_action_items = {'RSQUARE':([3,4,5,6,9,10,12,13,14,],[-5,-4,-2,-3,-9,13,-8,-7,-6,]),'CONST':([0,1,3,4,5,6,8,9,13,14,],[3,3,-5,-4,-2,-3,3,3,-7,-6,]),'LSQUARE':([0,1,3,4,5,6,8,9,13,14,],[1,1,-5,-4,-2,-3,1,1,-7,-6,]),'SYM':([0,1,3,4,5,6,8,9,13,14,],[5,5,-5,-4,-2,-3,5,5,-7,-6,]),'NUM':([0,1,3,4,5,6,8,9,13,14,],[6,6,-5,-4,-2,-3,6,6,-7,-6,]),'LPAREN':([0,1,3,4,5,6,8,9,13,14,],[8,8,-5,-4,-2,-3,8,8,-7,-6,]),'RPAREN':([3,4,5,6,9,11,12,13,14,],[-5,-4,-2,-3,-9,14,-8,-7,-6,]),'$end':([2,3,4,5,6,7,13,14,],[-1,-5,-4,-2,-3,0,-7,-6,]),'STRING':([0,1,3,4,5,6,8,9,13,14,],[4,4,-5,-4,-2,-3,4,4,-7,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'term':([0,1,8,9,],[2,9,9,9,]),'list':([1,8,9,],[10,11,12,]),'statement':([0,],[7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> term','statement',1,'p_statement_term','Parsing.py',65),
  ('term -> SYM','term',1,'p_term_sym','Parsing.py',69),
  ('term -> NUM','term',1,'p_term_num','Parsing.py',72),
  ('term -> STRING','term',1,'p_term_string','Parsing.py',78),
  ('term -> CONST','term',1,'p_term_const','Parsing.py',81),
  ('term -> LPAREN list RPAREN','term',3,'p_term_appr','Parsing.py',86),
  ('term -> LSQUARE list RSQUARE','term',3,'p_term_expr','Parsing.py',89),
  ('list -> term list','list',2,'p_list','Parsing.py',92),
  ('list -> term','list',1,'p_list','Parsing.py',93),
]
